INSERT INTO User (name, email) 
VALUES 
	('Brandon Cardenas MD', 'BrandonCardenasMD@example.net'),
	('Kathleen Holland', 'KathleenHolland@example.com'),
	('Daniel Mason', 'DanielMason@example.net'),
	('Debra Sanders', 'DebraSanders@example.com'),
	('Brooke Nunez', 'BrookeNunez@example.org'),
	('Steven Taylor', 'StevenTaylor@example.net'),
	('Jacqueline White', 'JacquelineWhite@example.org'),
	('Kevin Mcbride', 'KevinMcbride@example.net'),
	('Richard Dean', 'RichardDean@example.org'),
	('Karen Walker', 'KarenWalker@example.org'),
	('Robert Williams', 'RobertWilliams@example.org'),
	('Regina Lopez', 'ReginaLopez@example.com'),
	('Donald Smith', 'DonaldSmith@example.com'),
	('Derrick Mathews', 'DerrickMathews@example.com'),
	('Mr. Isaac Willis', 'Mr.IsaacWillis@example.com'),
	('Paul Smith', 'PaulSmith@example.org'),
	('Christopher Stone', 'ChristopherStone@example.net'),
	('Mark Ellis', 'MarkEllis@example.com'),
	('Tiffany Collins', 'TiffanyCollins@example.org'),
	('Dawn Aguilar', 'DawnAguilar@example.org');
